services:
    Heptacom\HeptaConnect\Playground\ShopwarePlatform\Console\Command\Init:
        tags:
            - { name: 'console.command' }
        arguments:
            - '%env(DATABASE_URL)%'
            - '%kernel.project_dir%'
            - '@cache.object'
            - '@monolog.logger'
            - '@Shopware\Core\Framework\DataAbstractionLayer\Indexing\IndexerRegistryInterface'
            - '@Shopware\Core\Framework\DataAbstractionLayer\Indexing\EntityIndexerRegistry'
            - !tagged_iterator shopware.migration_source
