services:
    Heptacom\HeptaConnect\Core\Bridge\PortalNode\Configuration\InstructionFileLoader:
        tags:
            - { name: heptaconnect_core.portal_node_configuration.instruction_file_loader }
        arguments:
            - '%kernel.project_dir%/config/portal_configs.php'

    Heptacom\HeptaConnect\Playground\ShopwarePlatform\Console\Command\Init:
        tags:
            - { name: 'console.command' }
        arguments:
            - '%env(DATABASE_URL)%'
            - '%kernel.project_dir%'
            - !tagged_iterator shopware.migration_source

    Heptacom\HeptaConnect\Playground\ShopwarePlatform\Console\Command\DemoData:
        tags:
            - { name: console.command }
        arguments:
            - '@Heptacom\HeptaConnect\Storage\Base\Contract\Action\PortalNode\PortalNodeCreateActionInterface'
            - '@Heptacom\HeptaConnect\Storage\Base\Contract\Action\PortalNodeAlias\PortalNodeAliasFindActionInterface'
