services:
    Heptacom\HeptaConnect\Playground\ShopwarePlatform\Console\Command\Init:
        tags:
            - { name: 'console.command' }
        arguments:
            - '%env(DATABASE_URL)%'
            - '%kernel.project_dir%'
            - '@cache.object'
            - '@monolog.logger'
            - '@Shopware\Core\Framework\DataAbstractionLayer\Indexing\IndexerRegistryInterface'
            - '@Shopware\Core\Framework\DataAbstractionLayer\Indexing\EntityIndexerRegistry'
            - '@Shopware\Core\System\User\Service\UserProvisioner'
            - !tagged_iterator shopware.migration_source

    Heptacom\HeptaConnect\Playground\ShopwarePlatform\Console\Command\DemoData:
        tags:
            - { name: console.command }
        arguments:
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\StorageKeyGenerator'
            - '@heptaconnect_bridge_key_alias.repository'
            - '@Heptacom\HeptaConnect\Storage\ShopwareDal\Repository\PortalNodeRepository'
