services:
    bottleHealthService:
        public: true
        class: Heptacom\HeptaConnect\Playground\Portal\BottleHealthService
    Heptacom\HeptaConnect\Portal\Base\StatusReporting\StatusReporterCollection:
        public: true
        arguments:
            - !tagged statusReporter
    bottleStatusReporter:
        tags: ['statusReporter']
        class: Heptacom\HeptaConnect\Playground\Portal\BottleStatusReporter
        arguments: ['@portal', '@bottleHealthService', '@Psr\Log\LoggerInterface']
